name: 'Invite a list of users to a GitHub Organization'

inputs:
  admin-pat:  
    description: 'A personal access token with [admin:org] scope'
    required: true
  org:
    description: 'The name of the organization to create the team in'
    required: true
  name:
    description: 'The name of the team to create'
    required: true
  visibility:
    description: 'The visibility of the team (secret or closed)'
    default: closed

runs:
  using: "composite"
  steps:
    - name: Print details
      shell: bash
      run: echo "Creating team $TEAM in organization $ORG"
      env:
        ORG: ${{ inputs.org }}
        TEAM: ${{ inputs.name }}
        
    - name: Invite users
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.admin-pat }}
        script: |
          const org = '${{ inputs.org }}';
          const name = '${{ inputs.name }}';
          const visibility = '${{ inputs.visibility }}';
         
          console.log(`Creating team ${name} ...`);

          try {
            const existingTeam = await github.rest.teams.getByName({
              org: org,
              team_slug: name
            });

            if (existingTeam.data) {
              console.log(`   skipping team already exists.`);
              return;
            }
          } catch (error) {
            if (error.status !== 404) {
              console.log(`Error checking for team ${name}: ${error.message}`);
              throw error;
            }
          }

          try {
            await github.rest.teams.create({
              org: org,
              name: name,
              privacy: visibility
            });
          } catch (error) {
            console.log(`Error creating team ${name}: ${error.message}`);
            throw error;
          }